# Generated by Django 4.1.3 on 2022-11-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Speakers', 'Колонки'), ('Keyboard', 'Клавиатура'), ('monitor', 'Монитор'), ('other', 'Разное')], default='Speakers', max_length=15, verbose_name='Status')),
                ('rot', models.PositiveIntegerField(default=1, verbose_name='Rot')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
    ]
