# Generated by Django 4.1.3 on 2022-11-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_store_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9999999, verbose_name='Price'),
        ),
    ]
