# Generated by Django 4.1.3 on 2022-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_store_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
