# Generated by Django 4.1.3 on 2022-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_store_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rot',
        ),
        migrations.AddField(
            model_name='store',
            name='remainder',
            field=models.PositiveIntegerField(default=12, verbose_name='Remainder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
