# Generated by Django 4.1.3 on 2022-12-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_store_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=90, null=True, verbose_name='Quantity')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='webapp.store', verbose_name='Good')),
            ],
        ),
    ]
