# Generated by Django 4.1.3 on 2022-12-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_goodincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodincart',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, max_length=90, null=True, verbose_name='Quantity'),
        ),
    ]
